version: '3.4'  

services:
  api:
    build: 
      context: server/
      target: devlopment
    volumes:
      - ./server:/app/api
      - /app/node_modules/
    ports:
      - 3000:3000
    command: npm run dev

  ui:
    build: 
      context: client/
      target: devlopment
    volumes:
      - ./client:/app/ui
      - /app/node_modules/
    ports:
      - 5173:5173
    command: npm run dev
    