version: '3.4'  

services:
  api:
    build: 
      context: server/
      target: devlopment
    volumes:
      - ./server:/app
      - /app/node_modules/
    ports:
      - 3000:3000
    command: npm run dev
