version: '3.8'

services:
  api:
    build: 
      context: server/
      target: production
    ports:
      - 3000:3000
  ui:
    build: 
      context: client/
      target: production
    depends_on:
      - api
    ports:
      - 8080:8080