version: '3.4'  

services:
  api:
    build: 
      context: server/
      target: devlopment
    volumes:
      - ./server:/app/api
      - /app/api/node_modules/
    ports:
      - 3000:3000
    command: npm run dev

  ui:
    build: 
      context: client/
      target: devlopment
    volumes:
      - ./client:/app/ui
      - /app/ui/node_modules/
    ports:
      - 8080:8080
    depends_on:
      - api
    command: npm run dev
    