version: '3.8'

services:
  api:
    build: 
      context: server/
      target: production
    ports:
      - 3000:3000
  ui:
    depends_on:
      - api
    build: 
      context: client/
      target: production
    ports:
      - 8080:8080
  nginx:
    depends_on:
      - ui
      - api
    build: 
      context: nginx/ 
    ports:
      - 80:80

