version: '3.5'

services:
  api:
    build: 
      context: /server
      target: production
    ports:
      - 3000:3000
  ui:
    build: 
      context: client/
      target: devlopment
    ports:
      - 8080:8080